name: Integracja.Server.Api Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Integracja.Server.Api
    - name: Build
      run: dotnet build Integracja.Server.Api -c Release --no-restore
    - name: Publish
      run: dotnet publish Integracja.Server.Api -o ${{env.DOTNET_ROOT}}/publish
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'integracja-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a4830e98d59845459c74c90794461d22 }}
        package: ${{env.DOTNET_ROOT}}/publish
