name: Integracja.Server.Web Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Integracja.Server.Web
    - name: Build
      run: dotnet build src/Integracja.Server.Web -c Release --no-restore
    - name: Publish
      run: dotnet publish src/Integracja.Server.Web -o ${{env.DOTNET_ROOT}}/publish
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'integracja-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_172d821db2cb43d79cb6bcd6a8551c25 }}
        package: ${{env.DOTNET_ROOT}}/publish
